### PR TITLE
#13: Step 6 (closes #13)

### LINKED ISSUE #13: Step 6
Use wiro to define the routes

### PR DESCRIPTION
**Pull request by tpetrucciani**
Closes #13

### tests performed

Manual testing using the client from the solution and on command line (also for invalid requests).

### CODE REVIEW

**Comment by tpetrucciani** [comment]
Right, I've added a bit of text.

By the way, testing with a wrong request (`{"userMove": "wrong"}`) I get
```
Failed decoding of '' of type 'Expected a value of type Move, but got wrong'
```

Is there something missing in the quotes before "of type"? Should I do something to get `userMove` in there maybe?

**Comment by gabro** [comment]
That's a good question, @calippo do you have any idea?

**Comment by calippo** [comment]
I don't think there's something you can do about it.

Query params are decoded in two steps:
1. the query params are extracted using akka parameterMap
2. the contained value is parsed with circe to extract the proper value

`wrong`, is a root json object in your case, that's why the history is empty.
It's kind of a wiro bug.

**Comment by calippo** [comment]
I'm not fixing it now because we are rewriting wiro... but we should at least fix the error message in case the path is empty ;P

**Pull request merged**
